spring:
  application:
    name: ding-b
server:
  port: 11000

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      dispatch-version: 2018
  client:
    serviceUrl:
      defaultZone: http://registry:123456@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
#security:
#  user:
#    name: registry
#    password: 123456
#  basic:
#    enabled: true