spring:
  application:
    name: ding-a
server:
  port: 20000

eureka:
  instance:
    prefer-ip-address: true
#    metadata-map:
#      dispatch-version: true
  client:
    serviceUrl:
      defaultZone: http://registry:123456@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
#security:
#  user:
#    name: registry
#    password: 123456
#  basic:
#    enabled: true